### ISSUE TITLE
LaTeX not formatted correctly

### ISSUE THREAD

**Issue by conordaly0** [matlab-deep-learning/SciML-and-Physics-Informed-Machine-Learning-Examples#1]
The LaTeX formatting in the Neural Operator section of the main README looks like it's not rendered correctly. Elsewhere it looks OK so it may just be a missed character somewhere.

**Comment by bwdGitHub** [comment]
I couldn't quite work it out, markdown uses underscores to italicize, and LaTeX uses them for subscripts. These seemed to be conflicting on GitHub, but not on the VS code markdown extension. I swapped the notation to have less subscripts and it seems OK now.
